In [34]:
import ast
import requests
from datetime import date, timedelta
list = []
class Krx:

    isin_code = 'KR7005930003'
    start_date = '2019/04/20'
    end_date = '2019/06/20'
    


    def main(self):

        start = date(int(self.start_date.split("/")[0]), int(self.start_date.split("/")[1]), int(self.start_date.split("/")[2]))
        end = date(int(self.end_date.split("/")[0]), int(self.end_date.split("/")[1]), int(self.end_date.split("/")[2]))

        delta = end - start

        day_price_data = self.get_day_price()
        short_stock_selling_data = self.get_short_stock_selling()

        for day in range(delta.days+1):
            d = start + timedelta(days=day)
            key = str(d).replace("-", "")
            if key in day_price_data:
                list.append([str(d).replace("-", "/"), day_price_data[key][0], day_price_data[key][1], day_price_data[key][2], 
                             day_price_data[key][3], day_price_data[key][4], short_stock_selling_data[key][2], short_stock_selling_data[key][3]])
       

    def get_day_price(self):

        otp = requests.get('http://marketdata.krx.co.kr/contents/COM/GenerateOTP.jspx?bld=MKD/04/0402/04020100/mkd04020100t3_02&name=chart')

        parameters = {
            'isu_cd': self.isin_code,
            'fromdate': self.start_date.replace("/", ""),
            'todate': self.end_date.replace("/", ""),
            'pagePath': '/contents/MKD/04/0402/04020100/MKD04020100T3T2.jsp',
            'code': otp.content
        }

        res = requests.post('http://marketdata.krx.co.kr/contents/MKD/99/MKD99000001.jspx', parameters)

        data = ast.literal_eval(res.text)['block1']

        result = {}

        for item in data:
            # tdd_clsprc : 종가
            # acc_trdval : 거래대금
            # tdd_opnprc : 시가
            # tdd_hgprc : 고가
            # tdd_lwprc : 저가
            result[item['trd_dd'].replace("/", "")] = (item['tdd_clsprc'], item['tdd_opnprc'], item['tdd_hgprc'], item['tdd_lwprc'], item['acc_trdval'])

        return result

    def get_short_stock_selling(self):

        # reverse engineered from the source at here https://finance.naver.com/item/short_trade.nhn?code=005930
        otp = requests.get('https://short.krx.co.kr/contents/COM/GenerateOTP.jspx?bld=SRT/02/02010100/srt02010100X&name=form')

        parameters = {
            'isu_cd': self.isin_code,
            'strt_dd': self.start_date.replace("/", ""),
            'end_dd': self.end_date.replace("/", ""),
            'pagePath': '/contents/SRT/02/02010100/SRT02010100X.jsp',
            'code': otp.content
        }

        res = requests.post('https://short.krx.co.kr/contents/SRT/99/SRT99000001.jspx', parameters)

        data = ast.literal_eval(res.text)['block1']

        result = {}

        for item in data:
            # cvsrtsell_trdvol : 공매도 거래량
            # str_const_val1 : 공매도 잔고량
            # cvsrtsell_trdval : 공매도 거래대금
            # str_const_val2 : 공매도 잔고금액
            result[item['trd_dd'].replace("/", "")] = (item['cvsrtsell_trdvol'], item['str_const_val1'], item['cvsrtsell_trdval'], item['str_const_val2'])

        return result


if __name__ == "__main__":
    Krx().main()

In [36]:
import pandas as pd
df = pd.DataFrame(list, columns=["년/월/일", "종가", "시가", "고가", "저가", "거래대금", "공매도거래대금", "공매도잔고금액"])

In [38]:
df.head()

,년/월/일,종가,시가,고가,저가,거래대금,공매도거래대금,공매도잔고금액
0,2019/04/22,"45,350","45,400","45,900","45,100","273,125,405,900","4,274,865,200","228,801,543,300"
1,2019/04/23,"45,200","45,050","45,500","45,000","313,179,774,125","26,153,015,200","235,840,808,400"
2,2019/04/24,"44,750","45,400","45,650","44,150","594,100,467,458","26,061,974,400","239,252,742,500"
3,2019/04/25,"44,650","44,250","45,000","44,100","485,378,095,190","12,385,413,750","233,646,261,350"
4,2019/04/26,"44,850","44,200","45,000","43,800","434,008,341,453","13,765,144,250","231,788,029,200"